files:
  - source: "/config/locales/views/about/en.yml"
    translation: "/config/locales/views/about/%two_letters_code%.yml"
  - source: "/config/locales/views/announcements/en.yml"
    translation: "/config/locales/views/announcements/%two_letters_code%.yml"